version: "3"

services:
  nginx:
    # nginx (ensure session + routing) -> backend
    image: openresty/openresty:1.19.3.1-1-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/public.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/session_id.lua:/usr/local/lib/nginx/lua/session_id.lua"
    links:
      - backend

  nginx-haproxy:
    # nginx (ensure session) -> haproxy (routing) -> backend
    image: openresty/openresty:1.19.3.1-1-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/combined.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/session_id.lua:/usr/local/lib/nginx/lua/session_id.lua"
    links:
      - private_haproxy

  haproxy:
    # haproxy (ensure session + routing) -> backend
    build: ./haproxy
    ports:
      - "8080:80"
    volumes:
      - "./haproxy/public.cfg:/usr/local/etc/haproxy/haproxy.cfg"
      - "./haproxy/session_id.lua:/usr/local/etc/haproxy/session_id.lua"
    links:
      - backend

  private_haproxy:
    # haproxy (routing only) -> backend
    image: haproxy:2.3.1
    ports:
      - "8082:80"
    volumes:
      - "./haproxy/routing.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    links:
      - backend

  backend:
    image: openresty/openresty:1.19.3.1-1-alpine
    ports:
      - "8081:80"
    volumes:
      - "./nginx/backend.conf:/etc/nginx/conf.d/default.conf"
